export class GlobalConstant{

     public static dico:Record<string,string> ={
        "asperge":"\\assets\\icone\\product\\asperge.png",
        "aubergine":"\\assets\\icone\\product\\aubergine.png",
        "brocoli":"\\assets\\icone\\product\\brocoli.png",
        "carotte":"\\assets\\icone\\product\\carotte.png",
        "cerise":"\\assets\\icone\\product\\cerise.png",
        "champignon":"\\assets\\icone\\product\\champignon.png",
        "chicon":"\\assets\\icone\\product\\chicon.png",
        "chou fleur":"\\assets\\icone\\product\\chou-fleur.png",
        "chou rouge":"\\assets\\icone\\product\\chou-rouge.png",
        "choux de bruxelles":"\\assets\\icone\\product\\choux-de-bruxelles.png",
        "concombre":"\\assets\\icone\\product\\concombre.png",
        "courgette":"\\assets\\icone\\product\\courgette.png",
        "fraise":"\\assets\\icone\\product\\fraise.png",
        "groseille":"\\assets\\icone\\product\\groseille.png",
        "haricot":"\\assets\\icone\\product\\haricot.png",
        "melon":"\\assets\\icone\\product\\melon.png",
        "mure":"\\assets\\icone\\product\\mure.png",
        "myrtille":"\\assets\\icone\\product\\myrtille.png",
        "petit pois":"\\assets\\icone\\product\\petit-pois.png",
        "poire":"\\assets\\icone\\product\\poire.png",
        "poireau":"\\assets\\icone\\product\\poireau.png",
        "pomme de terre":"\\assets\\icone\\product\\pomme-de-terre.png",
        "potiron":"\\assets\\icone\\product\\potiron.png",
        "prune":"\\assets\\icone\\product\\prune.png",
        "salade":"\\assets\\icone\\product\\salade.png",
        "laitue":"\\assets\\icone\\product\\salade.png",
        "tomate":"\\assets\\icone\\product\\tomate.png",
    };
     public static dicoPopUp:Record<string,string> ={
        "asperge":"\\assets\\icone\\productPopUp\\asperge.png",
        "aubergine":"\\assets\\icone\\productPopUp\\aubergine.png",
        "brocoli":"\\assets\\icone\\productPopUp\\brocoli.png",
        "carotte":"\\assets\\icone\\productPopUp\\carotte.png",
        "cerise":"\\assets\\icone\\productPopUp\\cerise.png",
        "champignon":"\\assets\\icone\\productPopUp\\champignon.png",
        "chicon":"\\assets\\icone\\productPopUp\\chicon.png",
        "chou fleur":"\\assets\\icone\\productPopUp\\chou-fleur.png",
        "chou rouge":"\\assets\\icone\\productPopUp\\chou-rouge.png",
        "choux de bruxelles":"\\assets\\icone\\productPopUp\\choux-de-bruxelles.png",
        "concombre":"\\assets\\icone\\productPopUp\\concombre.png",
        "courgette":"\\assets\\icone\\productPopUp\\courgette.png",
        "fraise":"\\assets\\icone\\productPopUp\\fraise.png",
        "groseille":"\\assets\\icone\\productPopUp\\groseille.png",
        "haricot":"\\assets\\icone\\productPopUp\\haricot.png",
        "melon":"\\assets\\icone\\productPopUp\\melon.png",
        "mure":"\\assets\\icone\\productPopUp\\mure.png",
        "myrtille":"\\assets\\icone\\productPopUp\\myrtille.png",
        "petit pois":"\\assets\\icone\\productPopUp\\petit-pois.png",
        "poire":"\\assets\\icone\\productPopUp\\poire.png",
        "poireau":"\\assets\\icone\\productPopUp\\poireau.png",
        "pomme de terre":"\\assets\\icone\\productPopUp\\pomme-de-terre.png",
        "potiron":"\\assets\\icone\\productPopUp\\potiron.png",
        "prune":"\\assets\\icone\\productPopUp\\prune.png",
        "salade":"\\assets\\icone\\productPopUp\\salade.png",
        "laitue":"\\assets\\icone\\productPopUp\\salade.png",
        "tomate":"\\assets\\icone\\productPopUp\\tomate.png",
    };
}
